### ISSUE TITLE
Bug: TypeError: ProtectorObservable.dispatch() missing 1 required positional argument: 'module'

### ISSUE THREAD

**Issue by SORROWMX** [xFGhoul/PythonProtector#8]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/xFGhoul/PythonProtector/tree/dev/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/xFGhoul/PythonProtector/blob/dev/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/xFGhoul/PythonProtector/issues) that already report this problem, without success.

### Current Behavior

when pyrotector detect pefile installed i got this error

### Expected Behavior

close programm idk

### Steps to Reproduce

install pefile

### Full Traceback

Traceback (most recent call last):   File "C:\Users\SORROW\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner     self.run()   File "C:\Users\SORROW\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run     self._target(*self._args, **self._kwargs)   File "C:\Users\SORROW\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyprotector\modules\miscellaneous.py", line 387, in StartChecks     self.CheckImports()   File "C:\Users\SORROW\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyprotector\modules\miscellaneous.py", line 223, in CheckImports     self.event.dispatch( TypeError: ProtectorObservable.dispatch() missing 1 required positional argument: 'module'

**Comment by xFGhoul** [comment]
can you try again on `master` and tell me if this still happens?

edit: I will be updating this module tomorrow godwilling with it's much needed patches and fixes

**Comment by xFGhoul** [comment]
Hey there, just pushed an commit to master that should hopefully update this module to a somewhat usable version..going to bed now.
